<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css">
<script src="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@1.2/dist/Meting.min.js"></script>
<div class="aplayer"
    data-id="894935550"
    data-server="netease"
    data-type="playlist"
    data-autoplay="false"
    data-listfolded="true"
    data-listmaxheihgt="240px">
</div>
